matrix:
  include:
  - name: Hugo Min Cards
    env:
    - latest=false
    - config=cards.toml
  - name: Hugo Min Posts
    env:
    - latest=false
    - config=posts.toml
  - name: Hugo Latest Cards
    if: type=push
    env:
    - latest=true
    - config=cards.toml
  - name: Hugo Latest Posts
    if: type=push
    env:
    - latest=true
    - config=posts.toml
  exclude:
  - env: latest=true
    if: type=pull_request

install:
- make install_hugo

script:
- make build config=$config
